#!/usr/bin/env python3
"""
PANTE i18n build script
- Reads html/js/i18n.en.js (English source — the ONLY file you edit)
- Translates each key to 14 target languages via Google Translate (free, no API key)
- Writes html/js/i18n.js (consumed by script.js)

Usage:  python3 scripts/build_i18n.py
"""
import re, json, sys, time, urllib.parse, urllib.request

SRC = "html/js/i18n.en.js"
OUT = "html/js/i18n.js"

# target languages (code: google tl code)
LANGS = {
    "zh": "zh-CN",
    "id": "id",
    "vi": "vi",
    "hi": "hi",
    "es": "es",
    "fr": "fr",
    "de": "de",
    "pt": "pt",
    "ru": "ru",
    "ja": "ja",
    "ko": "ko",
    "ar": "ar",
    "tr": "tr",
    "tl": "tl",
}

def read_en(path):
    src = open(path, encoding="utf-8").read()
    m = re.search(r"window\.I18N_EN\s*=\s*\{(.*)\};", src, re.S)
    block = m.group(1)
    pairs = dict(re.findall(r'"([^"]+)":\s*"((?:[^"\\]|\\.)*)"', block))
    # unescape
    out = {}
    for k, v in pairs.items():
        out[k] = v.encode().decode("unicode_escape") if "\\" in v else v
    return out

def gtranslate(text, tl):
    q = urllib.parse.quote(text)
    url = f"https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl={tl}&dt=t&q={q}"
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=10) as r:
        data = json.loads(r.read().decode())
    return "".join(seg[0] for seg in data[0])

def main():
    en = read_en(SRC)
    keys = list(en.keys())
    print(f"EN source: {len(keys)} keys")
    result = {"en": en}
    for code, tl in LANGS.items():
        print(f"Translating -> {code}...", flush=True)
        d = {}
        for k in keys:
            try:
                d[k] = gtranslate(en[k], tl)
            except Exception as e:
                print(f"  ! {k}: {e}")
                d[k] = en[k]  # fallback to EN
            time.sleep(0.05)  # be gentle
        result[code] = d
        print(f"  done ({len(d)} keys)", flush=True)
    # write output
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by scripts/build_i18n.py — do not edit by hand.\n")
        f.write("// Edit html/js/i18n.en.js (English) then run the build script.\n")
        f.write("window.I18N = {\n")
        for code, d in result.items():
            f.write(f'  "{code}": {{\n')
            items = list(d.items())
            for i, (k, v) in enumerate(items):
                comma = "," if i < len(items) - 1 else ""
                v_esc = v.replace("\\", "\\\\").replace('"', '\\"')
                f.write(f'    "{k}": "{v_esc}"{comma}\n')
            f.write("  },\n")
        f.write("};\n")
    print(f"Written {OUT}")

if __name__ == "__main__":
    main()
